### ISSUE TITLE
Error when trying to use

### ISSUE THREAD

**Issue by Harmsly** [dragos240/Pocket-NLSE#1]
I'm trying to use the latest build, but when I select "eShop/CIA version" it gives me an error that says Error: 0xC8AO4555, main.c:72" then it tells me to press A which closes it
I've tried deleting and reinstalling but it tells me the same thing

**Comment by Harmsly** [comment]
Forgot to mention I'm using the CIA version, not the 3dsx version if it matters

**Comment by dragos240** [comment]
Strange. I've literally never seen that error ever before. Not in my program, nor in anyone else's program. And knowing whether it's the CIA version of .3dsx version DOES actually matter. They work slightly differently. That's good to know. Had to look up the error. Sounds like you might be using Gateway. Is that true? It won't work with Gateway evidently. JKSM has the same problem.

**Comment by Harmsly** [comment]
I'm using luma
I am using JKSM to extract saves so is that why it isn't working? It did work before but it just started giving me that error a week or two ago for seemingly no reason

**Comment by dragos240** [comment]
Does JKSM still work? And the latest build actually gets rid of the old import save file functionality. It now dumps the save cartridge save file and you inject it. It's possible you're using an old build. Even then, though, I don't know why you'd be getting this error. Do you know anything you might have changed?

**Comment by Harmsly** [comment]
I just updated to the latest version and it works now, I guess I didn't have the latest one *facepalm*

**Comment by dragos240** [comment]
Well, that's good that your problem's solved. Have a great day.
